kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.green.frontend_deployment_name }}
  labels:
    app: {{ .Values.green.labels.app }}
spec:
  replicas: {{ .Values.green.frontend_replicas }}
  selector:
    matchLabels:
      app: {{ .Values.green.labels.app }}
  template:
    metadata:
      name: {{ .Values.green.frontend_deployment_name }}
      labels:
        app: {{ .Values.green.labels.app }}
        role: frontend
        env: {{ .Values.green.labels.env }}
    spec:
      containers:
      - name: {{ .Values.green.frontend_deployment_name }}
        image: gcr.io/{{ .Values.project }}/{{ .Values.green.image.name }}:{{ .Values.green.image.tag }}
        resources:
          limits:
            memory: {{ .Values.deployment.webapp_frontend.resources.limit.memory }}
            cpu: {{ .Values.deployment.webapp_frontend.resources.limit.cpu }}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.webapp_frontend.readinessProbe.path }}
            port: {{ .Values.deployment.webapp_frontend.readinessProbe.port }}
        env:
        - name: COMPONENT
          value: frontend
        - name: BACKEND_URL
          value: http://webapp-backend:8080/metadata
        - name: VERSION
          value: green
