kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.blue.backend_deployment_name }}
  labels:
    app: {{ .Values.blue.labels.app }}
spec:
  replicas: {{ .Values.blue.backend_replicas }}
  selector:
    matchLabels:
      app: {{ .Values.blue.labels.app }}
  template:
    metadata:
      name: {{ .Values.blue.backend_deployment_name }}
      labels:
        app: {{ .Values.blue.labels.app }}
        role: backend
        env: {{ .Values.blue.labels.env }}
    spec:
      containers:
      - name: {{ .Values.blue.backend_deployment_name }}
        image: gcr.io/{{ .Values.project }}/{{ .Values.blue.image.name }}:{{ .Values.blue.image.tag }}
        resources:
          limits:
            memory: {{ .Values.deployment.webapp_backend.resources.limit.memory }}
            cpu: {{ .Values.deployment.webapp_backend.resources.limit.cpu }}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.webapp_backend.readinessProbe.path }}
            port: {{ .Values.deployment.webapp_backend.readinessProbe.port }}
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: blue
#        ports:
#        - name: backend
#          containerPort: 8080