kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: webapp-frontend-canary
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: frontend
      labels:
        app: webapp
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: gcr.io/{{ .Values.project }}/webapp:{{ .Values.canary.image.tag }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: frontend
        - name: BACKEND_URL
          value: http://webapp-backend:8080/metadata
          #value: http://webapp-backend-canary:8080/metadata
        - name: VERSION
          value: canary
        ports:
        - name: frontend
          containerPort: 8080