steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/cicd-istio-spinnaker/webapp:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cicd-istio-spinnaker/webapp:$TAG_NAME']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['run', 'gcr.io/cicd-istio-spinnaker/webapp', 'go', 'test']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'python_server/helm/*', 'gs://cicd-istio-spinnaker-kubernetes-manifests']
images: ['gcr.io/cicd-istio-spinnaker/webapp:$TAG_NAME']


