kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-canary
  labels:
    app: webapp-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: frontend
      labels:
        app: webapp
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: gcr.io/cicd-istio-spinnaker/sample-app:v1.0.2.1 # Change tag
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 5000
#        env:
#        - name: COMPONENT
#          value: frontend
#        - name: BACKEND_URL
#          value: http://sample-backend-canary:8080/metadata
#        - name: VERSION
#          value: canary
        ports:
        - name: frontend
          containerPort: 5000