apiVersion: networking.istio.io/v1alpha3 
kind: DestinationRule 
metadata: 
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }} 
spec: 
  host: {{ .Values.name }} 
  trafficPolicy: 
    tls: 
      mode: ISTIO_MUTUAL 
  subsets: 
    - name: {{ .Values.main.labels.env }} 
      labels: 
        env: {{ .Values.main.labels.env }}  
    - name: {{ .Values.canary.labels.env }}  
      labels: 
        env: {{ .Values.canary.labels.env }} 