gcs:
  enabled: true
  bucket: cicd-istio-spinnaker-spinnaker-config
  project: cicd-istio-spinnaker
  jsonKey: '{
  "type": "service_account",
  "project_id": "cicd-istio-spinnaker",
  "private_key_id": "c5bf21fffa1c1567e0b72b009ce962a6a867c716",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDbq0vsapEqwG2t\nvoNaVKmj3VNNjI1gLR0VstpWmIqT84yMTiVV+qA2LH+LIgNXxfZx+cP13f/evMDz\ntOpZGkJ79dJ0X0jGoMmuhUA4McL+6WnBnRCRkVLUz539XdjlLgIAMjYIQNmuvRqj\nVZWkJAYM47+lXrDUXVO/tdk21T50pcg/OHn+Te8/BJMsHtHU/TDJbTw8zvOVkTZA\n4F+e94lNWADtWf7lX9UTXUFYdhMPaqrIHmv8YgQJE7pSYq+rSKIn+Bo3eFccKGqA\nAsAlhKVdf+js+asFv3jweKwEgquVFariw71GH77tTcYIWmDF1w/2jruGhhvoQm6H\nvX9cBdKBAgMBAAECggEACU+3hiv2P1Os0oKS2s9f6XxGPbFJhNwksXjFXIpWxXK7\ncG8Xkg9vnxw/w8wLTDst+SLXNaLVZ8GkhDAVBvXf/5Up+JjZYuIJ6oXndPpXA6st\nOnHH9AOu+SpbzhOeUAilORDnzW3CTG/joyzLjQuh3gYBZ6cd48KY/DVfIb3kSdlx\nBRXMMkUZ4bZnwD7L3exhoPfuPjCTgptPUTRNnZyiyJWN7mOGO9ZXoBixXeLKYptA\nkLevkLdBn2MusL0DB9aunGux+wRkZY78hYczJrkKXe2D0BlY6xWGCmysek2rIZdb\nJT1APmzhlcoukfxoaK88Ie/NAUgBc9e1ROqh+TVr6QKBgQD4qKRVf3bVH4lPKI7a\nIRJ3MgZeoex1l7onsNWpEQDvqohCYguB6P8kgc0pC2/inYCwqcPm839axDnNvkUy\n35YCMzHtLZqHO3ndB+kKXV85nrpatpWaQ912QS57wnRNk3u06CQg+DA+QUjeZ0WX\nk8aLaf9wTjCpnBuZHu/VdmSwJwKBgQDiJ400hhfHeq+oZnveM81HA3H/IzH0kzxu\nic95vdwGFE/5KJGzyIjq8/PagVo1G7FJjpKFvCOBZlIVgGwF1yayGcqP8d9XKYoN\ng42TUukNedo4uvvW2IL9WDtcZrgqGbNTvEqxh4T5JVBAohjN4wfHtmc2emf+YilP\nuwM257ZpFwKBgQCfQ6S9/j4mk2RnBxs4KyagobHiuuOxDdV1xpWTDAkFeLx9iD7G\nnm2M/HZja6fmBet/O7z2F8/iWvyLAutfgkWacx/vQd5P75BGOeLReKydQ0UpBPkd\nLYqTS3xyWEIVzfjWDjnVxCFiPn5ltM+mHkh00xeA3xPcDti+YkpK9uHW0QKBgQCu\n6spzYneH6SNty35o2YYfM9H69TzRHwQxttNLJQbFiPZmDvPKqwMDPpZQXZXo17di\n3iwD1gVcM0ivqrliNwuN2xbqCLimkNFfLG3XEdyBeMrI8A6TGLkPvCuFh0lP/rrN\nvCfFcbzueua8ZuNqcvt0g2cHItvGTCQJr+qHj+ZtFwKBgC+ouV9l4Xf9dK+4PlOK\nyThrtIX35GXJgJSQCpZmUAv9+22slq4/r5yFocp0wKvOUK+QDu79EqESf1v83QhQ\nMBJPdrL1bAfHMNdZ5t3jHLhpofw9AhuWAjCFtT8O8fDtZu3pKbQl4t7j374XBvy5\nqGUsvOLzshWhKmYV23kRWtVZ\n-----END PRIVATE KEY-----\n",
  "client_email": "spinnaker-account@cicd-istio-spinnaker.iam.gserviceaccount.com",
  "client_id": "115524776591524425647",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/spinnaker-account%40cicd-istio-spinnaker.iam.gserviceaccount.com"
}'

dockerRegistries:
- name: gcr
  address: https://gcr.io
  username: _json_key
  password: '{
  "type": "service_account",
  "project_id": "cicd-istio-spinnaker",
  "private_key_id": "c5bf21fffa1c1567e0b72b009ce962a6a867c716",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDbq0vsapEqwG2t\nvoNaVKmj3VNNjI1gLR0VstpWmIqT84yMTiVV+qA2LH+LIgNXxfZx+cP13f/evMDz\ntOpZGkJ79dJ0X0jGoMmuhUA4McL+6WnBnRCRkVLUz539XdjlLgIAMjYIQNmuvRqj\nVZWkJAYM47+lXrDUXVO/tdk21T50pcg/OHn+Te8/BJMsHtHU/TDJbTw8zvOVkTZA\n4F+e94lNWADtWf7lX9UTXUFYdhMPaqrIHmv8YgQJE7pSYq+rSKIn+Bo3eFccKGqA\nAsAlhKVdf+js+asFv3jweKwEgquVFariw71GH77tTcYIWmDF1w/2jruGhhvoQm6H\nvX9cBdKBAgMBAAECggEACU+3hiv2P1Os0oKS2s9f6XxGPbFJhNwksXjFXIpWxXK7\ncG8Xkg9vnxw/w8wLTDst+SLXNaLVZ8GkhDAVBvXf/5Up+JjZYuIJ6oXndPpXA6st\nOnHH9AOu+SpbzhOeUAilORDnzW3CTG/joyzLjQuh3gYBZ6cd48KY/DVfIb3kSdlx\nBRXMMkUZ4bZnwD7L3exhoPfuPjCTgptPUTRNnZyiyJWN7mOGO9ZXoBixXeLKYptA\nkLevkLdBn2MusL0DB9aunGux+wRkZY78hYczJrkKXe2D0BlY6xWGCmysek2rIZdb\nJT1APmzhlcoukfxoaK88Ie/NAUgBc9e1ROqh+TVr6QKBgQD4qKRVf3bVH4lPKI7a\nIRJ3MgZeoex1l7onsNWpEQDvqohCYguB6P8kgc0pC2/inYCwqcPm839axDnNvkUy\n35YCMzHtLZqHO3ndB+kKXV85nrpatpWaQ912QS57wnRNk3u06CQg+DA+QUjeZ0WX\nk8aLaf9wTjCpnBuZHu/VdmSwJwKBgQDiJ400hhfHeq+oZnveM81HA3H/IzH0kzxu\nic95vdwGFE/5KJGzyIjq8/PagVo1G7FJjpKFvCOBZlIVgGwF1yayGcqP8d9XKYoN\ng42TUukNedo4uvvW2IL9WDtcZrgqGbNTvEqxh4T5JVBAohjN4wfHtmc2emf+YilP\nuwM257ZpFwKBgQCfQ6S9/j4mk2RnBxs4KyagobHiuuOxDdV1xpWTDAkFeLx9iD7G\nnm2M/HZja6fmBet/O7z2F8/iWvyLAutfgkWacx/vQd5P75BGOeLReKydQ0UpBPkd\nLYqTS3xyWEIVzfjWDjnVxCFiPn5ltM+mHkh00xeA3xPcDti+YkpK9uHW0QKBgQCu\n6spzYneH6SNty35o2YYfM9H69TzRHwQxttNLJQbFiPZmDvPKqwMDPpZQXZXo17di\n3iwD1gVcM0ivqrliNwuN2xbqCLimkNFfLG3XEdyBeMrI8A6TGLkPvCuFh0lP/rrN\nvCfFcbzueua8ZuNqcvt0g2cHItvGTCQJr+qHj+ZtFwKBgC+ouV9l4Xf9dK+4PlOK\nyThrtIX35GXJgJSQCpZmUAv9+22slq4/r5yFocp0wKvOUK+QDu79EqESf1v83QhQ\nMBJPdrL1bAfHMNdZ5t3jHLhpofw9AhuWAjCFtT8O8fDtZu3pKbQl4t7j374XBvy5\nqGUsvOLzshWhKmYV23kRWtVZ\n-----END PRIVATE KEY-----\n",
  "client_email": "spinnaker-account@cicd-istio-spinnaker.iam.gserviceaccount.com",
  "client_id": "115524776591524425647",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/spinnaker-account%40cicd-istio-spinnaker.iam.gserviceaccount.com"
}'
  email: 1234@5678.com

# Disable minio as the default storage backend
minio:
  enabled: false

# Configure Spinnaker to enable GCP services
halyard:
  spinnakerVersion: 1.19.4
  image:
    repository: us-docker.pkg.dev/spinnaker-community/docker/halyard
    tag: 1.32.0
    pullSecrets: []
  additionalScripts:
    create: true
    data:
      enable_gcs_artifacts.sh: |-
        $HAL_COMMAND config artifact gcs account add gcs-cicd-istio-spinnaker --json-path /opt/gcs/key.json
        $HAL_COMMAND config artifact gcs enable
      enable_pubsub_triggers.sh: |-
        $HAL_COMMAND config pubsub google enable
        $HAL_COMMAND config pubsub google subscription add gcr-triggers           --subscription-name gcr-triggers           --json-path /opt/gcs/key.json           --project cicd-istio-spinnaker           --message-format GCR
