apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.service.webapp_frontend.name }}
spec:
  ports:
  - name: {{ .Values.service.webapp_frontend.ports.webapp.name }}
    port: {{ .Values.service.webapp_frontend.ports.webapp.port }}
    protocol: TCP
    targetPort: {{ .Values.service.webapp_frontend.ports.webapp.targetPort }}
  selector:
    app: {{ .Values.service.webapp_frontend.selector.app }}
    role: {{ .Values.service.webapp_frontend.selector.role }}
  sessionAffinity: None
  type: {{ .Values.service.webapp_frontend.type }}
