apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.service.webapp_backend.name }}
spec:
  ports:
  - name: {{ .Values.service.webapp_backend.ports.webapp.name }}
    port: {{ .Values.service.webapp_backend.ports.webapp.port }}
    protocol: TCP
    targetPort: {{ .Values.service.webapp_backend.ports.webapp.targetPort }}
  selector:
    app: {{ .Values.service.webapp_backend.selector.app }}
    role: {{ .Values.service.webapp_backend.selector.role }}
  sessionAffinity: None
  type: {{ .Values.service.webapp_backend.type }}
