apiVersion: networking.istio.io/v1alpha3 
kind: VirtualService 
metadata: 
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.webapp_frontend.name }}
spec: 
  hosts: 
  - "*" 
  gateways: 
  - {{ .Values.gateway.name }}
  http: 
#  - match: 
#    - uri: 
#        exact: / 
    - route: 
      - destination: 
          host: {{ .Values.service.webapp_frontend.name }}
          port: 
            number: {{ .Values.service.webapp_frontend.ports.webapp.port }}
          subset: {{ .Values.blue.labels.env }}
        weight: {{ sub 100 .Values.frontend_percentage_blue }}
      - destination: 
          host: {{ .Values.service.webapp_frontend.name }}
          port: 
            number: {{ .Values.service.webapp_frontend.ports.webapp.port }}
          subset: {{ .Values.green.labels.env }}
        weight: {{ .Values.frontend_percentage_blue }}
