apiVersion: networking.istio.io/v1alpha3 
kind: VirtualService 
metadata: 
  namespace: {{ .Values.namespace }}
  name: webapp-backend 
spec: 
  hosts: 
  - webapp-backend 
  http: 
#  - match: 
#    - uri: 
#        exact: / 
    - route: 
      - destination: 
          host: webapp-backend
          port: 
            number: 8080
          subset: production
        weight: {{ sub 100 .Values.backend_percentage_canary }}
      - destination: 
          host: webapp-backend
          port: 
            number: 8080
          subset: {{ .Values.canary.labels.env }}
        weight: {{ .Values.backend_percentage_canary }}
